df,df2,df3 = combine_dataframe.get_combinedSongs()

In [7]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing  import  StandardScaler
import numpy as np

In [9]:
import combine_dataframe

In [173]:
df = pd.read_csv('../data/Playlist-5S8SJdl1BDc0ugpkEvFsIL.csv')
df.head()


setnumber             Title                      id  danceability  energy  \
0          1  ...Ready For It?  2yLa0QULdQr0qAIvVwN6B5         0.613   0.764   
1          2      Life Changes  4Vxu50qVrQcycjRyJQaZLC         0.687   0.845   
2          3         24K Magic  6b8Be6ljOzmkOmFslEb23P         0.818   0.803   
3          4       Galway Girl  0afhq8XCExXpqazXczTSve         0.624   0.876   
4          5        Photograph  1HNkqx9Ahdgi1Ixy2xkKkL         0.614   0.379   

   key  loudness  mode  speechiness  acousticness  instrumentalness  liveness  \
0    2    -6.509     1       0.1360        0.0527          0.000000    0.1970   
1    7    -4.370     1       0.0576        0.1000          0.000000    0.0452   
2    1    -4.282     1       0.0797        0.0340          0.000000    0.1530   
3    9    -3.374     1       0.1000        0.0735          0.000000    0.3270   
4    4   -10.480     1       0.0476        0.6070          0.000464    0.0986   

   valence    tempo  
0    0.417  160.015  
1    0.809   87.972  
2    0.632  106.970  
3    0.781   99.943  
4    0.201  107.989

In [174]:
df_test = df.iloc[:,3:14]
df_test

danceability  energy  key  loudness  mode  speechiness  acousticness  \
0             0.613   0.764    2    -6.509     1       0.1360       0.05270   
1             0.687   0.845    7    -4.370     1       0.0576       0.10000   
2             0.818   0.803    1    -4.282     1       0.0797       0.03400   
3             0.624   0.876    9    -3.374     1       0.1000       0.07350   
4             0.614   0.379    4   -10.480     1       0.0476       0.60700   
...             ...     ...  ...       ...   ...          ...           ...   
10056         0.406   0.306    3   -10.482     1       0.0372       0.31300   
10057         0.362   0.507    1   -11.229     1       0.0394       0.01740   
10058         0.331   0.733    2    -8.671     1       0.0468       0.08870   
10059         0.352   0.911    1    -5.230     1       0.0747       0.00121   
10060         0.352   0.911    1    -5.230     1       0.0747       0.00121   

       instrumentalness  liveness  valence    tempo  
0              0.000000    0.1970    0.417  160.015  
1              0.000000    0.0452    0.809   87.972  
2              0.000000    0.1530    0.632  106.970  
3              0.000000    0.3270    0.781   99.943  
4              0.000464    0.0986    0.201  107.989  
...                 ...       ...      ...      ...  
10056          0.007900    0.0727    0.073  135.272  
10057          0.216000    0.1130    0.456  146.641  
10058          0.001740    0.9470    0.380  128.512  
10059          0.000000    0.0995    0.236  148.033  
10060          0.000000    0.0995    0.236  148.033  

[10061 rows x 11 columns]

In [175]:
scaler = StandardScaler()
scaler.fit(df_test)

StandardScaler()

In [176]:
df_scaled = scaler.transform(df_test)

In [198]:
df_scaled = pd.DataFrame(df_scaled, columns=df_test.columns)
df_scaled

danceability    energy       key  loudness     mode  speechiness  \
0          0.271795  0.501566 -0.896968  0.272997  0.72431     0.892597   
1          0.717228  0.860808  0.495686  0.752714  0.72431    -0.156966   
2          1.505766  0.674534 -1.175499  0.772450  0.72431     0.138893   
3          0.338008  0.998296  1.052747  0.976088  0.72431     0.410655   
4          0.277814 -1.205945 -0.339907 -0.617584  0.72431    -0.290838   
...             ...       ...       ...       ...      ...          ...   
10056     -0.974215 -1.529707 -0.618438 -0.618033  0.72431    -0.430066   
10057     -1.239067 -0.638253 -1.175499 -0.785563  0.72431    -0.400614   
10058     -1.425668  0.364078 -0.896968 -0.211877  0.72431    -0.301548   
10059     -1.299261  1.153524 -1.175499  0.559841  0.72431     0.071957   
10060     -1.299261  1.153524 -1.175499  0.559841  0.72431     0.071957   

       acousticness  instrumentalness  liveness   valence     tempo  
0         -0.640935         -0.403410  0.078142 -0.224629  1.393345  
1         -0.477985         -0.403410 -0.906465  1.349210 -1.154250  
2         -0.705356         -0.403410 -0.207252  0.638573 -0.482440  
3         -0.569278         -0.403410  0.921349  1.236793 -0.730930  
4          1.268636         -0.401529 -0.560102 -1.091846 -0.446406  
...             ...               ...       ...       ...       ...  
10056      0.255802         -0.371395 -0.728095 -1.605752  0.518380  
10057     -0.762543          0.471924 -0.466700 -0.068048  0.920412  
10058     -0.516914         -0.396359  4.942802 -0.373180  0.279331  
10059     -0.818318         -0.403410 -0.554264 -0.951324  0.969636  
10060     -0.818318         -0.403410 -0.554264 -0.951324  0.969636  

[10061 rows x 11 columns]

In [184]:
model = KMeans(n_clusters=8, random_state = 1234)

In [185]:
model.fit(df_scaled) 

KMeans(random_state=1234)

In [186]:
model.labels_

array([3, 4, 0, ..., 2, 3, 3], dtype=int32)

In [187]:
labels = model.predict(df_scaled)
labels

array([3, 4, 0, ..., 2, 3, 3], dtype=int32)

In [205]:
x_test = df_scaled.iloc[1, :]
x_test

danceability        0.717228
energy              0.860808
key                 0.495686
loudness            0.752714
mode                0.724310
speechiness        -0.156966
acousticness       -0.477985
instrumentalness   -0.403410
liveness           -0.906465
valence             1.349210
tempo              -1.154250
Name: 1, dtype: float64

In [206]:
x_test.values.reshape(1, -1)

array([[ 0.71722818,  0.86080827,  0.49568573,  0.75271392,  0.72430998,
        -0.15696561, -0.47798546, -0.40340985, -0.90646549,  1.34920969,
        -1.1542497 ]])

In [207]:
model.predict(x_test.values.reshape(1,-1))

/Users/danielfriedman/miniconda3/envs/ih_da/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  warnings.warn(


array([4], dtype=int32)

In [192]:
df['cluster']=labels

In [218]:
df.head(50)

setnumber                                              Title  \
0           1                                   ...Ready For It?   
1           2                                       Life Changes   
2           3                                          24K Magic   
3           4                                        Galway Girl   
4           5                                         Photograph   
5           6                          Havana (feat. Young Thug)   
6           7                                When I Was Your Man   
7           8                                      Gonna Fly Now   
8           9            Don't Wanna Know (feat. Kendrick Lamar)   
9          10                                  Thinking out Loud   
10         11                                    Everybody Talks   
11         12            We Are Never Ever Getting Back Together   
12         13                                          Bad Blood   
13         14                     Hall of Fame (feat. will.i.am)   
14         15                                           Payphone   
15         16                                              Sugar   
16         17                                    Stuck Like Glue   
17         18                                 That's What I Like   
18         19                                      Steal My Girl   
19         20  I'm the One (feat. Justin Bieber, Quavo, Chanc...   
20         21                                     Wildest Dreams   
21         22                                 Young Dumb & Broke   
22         23                                          Unwritten   
23         24                                   Ignition - Remix   
24         25                                       Free Fallin'   
25         26                                    Brown Eyed Girl   
26         27                                            It Girl   
27         28                                   Hey, Soul Sister   
28         29                                      Feel It Still   
29         30                                             Closer   
30         31  CAN'T STOP THE FEELING! (from DreamWorks Anima...   
31         32                             Kiss Me Thru The Phone   
32         33                     Uptown Funk (feat. Bruno Mars)   
33         34                                        Blank Space   
34         35  Moves Like Jagger - Studio Recording From "The...   
35         36                                               Roar   
36         37                                               Ymca   
37         38                                 You Belong With Me   
38         39                    All These Things That I've Done   
39         40                           I Knew You Were Trouble.   
40         41                                  Cake By The Ocean   
41         42                                      Call Me Maybe   
42         43                                                 22   
43         44                                   California Gurls   
44         45                                Welcome To New York   
45         46                                           Our Song   
46         47                                         Love Story   
47         48                                        Hey Stephen   
48         49                                              Style   
49         50                                       Shake It Off   

                   song_id  danceability  energy  key  loudness  mode  \
0   2yLa0QULdQr0qAIvVwN6B5         0.613   0.764    2    -6.509     1   
1   4Vxu50qVrQcycjRyJQaZLC         0.687   0.845    7    -4.370     1   
2   6b8Be6ljOzmkOmFslEb23P         0.818   0.803    1    -4.282     1   
3   0afhq8XCExXpqazXczTSve         0.624   0.876    9    -3.374     1   
4   1HNkqx9Ahdgi1Ixy2xkKkL         0.614   0.379    4   -10.480     1   
5   1rfofaqEpACxVEHIZBJe6W         0.765   0.523    2    -4.333     1   
6   0nJW01T7XtvILxQgC5J7

In [217]:
df.columns = ['setnumber', 'Title', 'song_id', 'danceability', 'energy', 'key', 'loudness',
       'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'cluster']

In [ ]:
def pirnt_song_web_links(ilst):
    ''' Prints songs clickable Spotify web links
    takes  ilst = list of song IDs strings as an input'''   
    for i in [ilst]:
        print('https://open.spotify.com/track/{}'.format(i))

In [222]:
file = open('../data/plists_categories.txt')
cats = file.read()

cats = cats.split(', ')

for j in [i for i in cats]:
    t_df=combine_dataframe.features_of_playlist(j)
    t_df.to_csv('../data/'+j)

In [25]:
pd.read_csv('../data/Data_daniel/Playlist-37i9dQZEVXbKuaTI1Z1Afx.csv')

setnumber                                           Title  \
0           1                                          Tek It   
1           2                                            RAVE   
2           3                                       As It Was   
3           4                      10 Things I Hate About You   
4           5                                    Soy El Unico   
5           6                              A Man Without Love   
6           7                                    Dear Alcohol   
7           8                 In Jesus Name (God Of Possible)   
8           9                             Préstame Tu Corazón   
9          10                            We'll Never Have Sex   
10         11                                     Tom's Diner   
11         12                                     Wild as Her   
12         13                                          OH NO!   
13         14                                          Hug Me   
14         15                                            Late   
15         16                                         Ferrari   
16         17                                Magenta Mountain   
17         18                                  Desde Mis Ojos   
18         19                                       Pantysito   
19         20            Big Energy (feat. DJ Khaled) - Remix   
20         21                                     Sleazy Flow   
21         22                           Waddup (feat. Polo G)   
22         23                         Messages from the Stars   
23         24                               cinderella's dead   
24         25                               Until I Found You   
25         26                                         Finesse   
26         27                   Come On, Let's Go (with Nigo)   
27         28              this is what heartbreak feels like   
28         29  You're a Fucking Bitch Hope You Know That Shit   
29         30                                 Numb Little Bug   
30         31                                  We Not Humping   
31         32                            Escape (feat. Hayla)   
32         33                                   Nobody Like U   
33         34                                        DIVE IN!   
34         35                                    Fall In Love   
35         36                                   Birthday Cake   
36         37                           Una Noche en Medellín   
37         38               Never Til Now (feat. Brett Young)   
38         39                                      In My Head   
39         40                                      After Dark   
40         41                                    X ÚLTIMA VEZ   
41         42                                    Highway Boys   
42         43                                       Diet Coke   
43         44                          IDGAF (with blackbear)   
44         45                                    The Rumbling   
45         46                      Love Me Back (Fayahh Beat)   
46         47                                   Stress Relief   
47         48                                         Sunroof   
48         49                                     From Austin   
49         50                                    Mar y Tierra   

                        id  danceability  energy  key  loudness  mode  \
0   751srcHf5tUqcEa9pRCQwP         0.423   0.913    8    -5.354     1   
1   01kfSdF9zfcDLri5sSWEoL         0.716   0.748    8    -6.060     1   
2   4LRPiXqCikLlN15c3yImP7         0.520   0.731    6    -5.338     0   
3   6Jkm5kUldvIqxzI1Pa7nXH         0.544   0.786    8    -2.970     1   
4   6HJIZUOiZDE814XMhRGSZN         0.708   0.449    4    -4.369     0   
5   0oUBuOO4g9P4lREqfqR5nq         0.538   0.467    2    -9.589     1   
6   1BbUq9wc4N2q53fR9S6NsZ         0.815   0.504    1    -9.617     1   
7   6Srgw41KlTpWtu5hbEKeja         0.504   0.706    6    -5.093     1   
8   1bnSKjuPEd8FPACxqA5Mos     